[Seat:*]
autologin-user=ribi
autologin-user-timeout=0
autologin-session=ribi-direct
user-session=ribi-direct
greeter-session=lightdm-gtk-greeter
minimum-vt=1
xserver-command=/usr/local/bin/ribi-xorg -nolisten tcp -noreset -keeptty -ac
session-wrapper=/usr/local/bin/ribi-session-wrapper
display-stopped-script=/usr/local/bin/ribi-dump-session
