Section "Module"
    Disable "glx"
EndSection
Section "ServerFlags"
    Option "AutoAddDevices" "true"
    Option "AllowMouseOpenFail" "false"
    Option "AutoEnableDevices" "true"
EndSection
Section "InputClass"
    Identifier "Ribi libinput pointer"
    MatchIsPointer "on"
    Driver "libinput"
EndSection
Section "InputClass"
    Identifier "Ribi libinput keyboard"
    MatchIsKeyboard "on"
    Driver "libinput"
EndSection
Section "Device"
    Identifier "Ribi QEMU Video"
    Driver "modesetting"
    Option "AccelMethod" "none"
EndSection
Section "Monitor"
    Identifier "Ribi Monitor"
    Option "PreferredMode" "1280x800"
EndSection
Section "Screen"
    Identifier "Ribi Screen"
    Device "Ribi QEMU Video"
    Monitor "Ribi Monitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Virtual 1280 800
        Modes "1280x800"
    EndSubSection
EndSection
